# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание 1

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [13]:
ans = a @ a.T

print(round(ans[0][0], 2))
print(ans)

1.58
[[1.57995312 0.48673782 1.28525324 0.9947397  0.64675177]
 [0.48673782 0.40706809 0.26368252 0.57840584 0.55984141]
 [1.28525324 0.26368252 1.11497408 0.64198458 0.34157207]
 [0.9947397  0.57840584 0.64198458 1.44251562 0.77015453]
 [0.64675177 0.55984141 0.34157207 0.77015453 0.77110897]]


In [14]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [15]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание 2

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [21]:
nums = np.arange(1, 10000 + 1)

squared = np.sum(nums ** 2)

squared

333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [29]:
x = torch.rand(5, 3)
x

tensor([[0.7882, 0.3607, 0.2985],
        [0.8602, 0.3751, 0.5066],
        [0.7597, 0.1851, 0.0598],
        [0.3149, 0.6439, 0.6293],
        [0.2246, 0.2080, 0.6142]])

In [23]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [24]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.3834, 5.4168, 5.4609],
        [5.0767, 5.2021, 5.4477],
        [5.6499, 5.4505, 5.3690],
        [5.7382, 5.9783, 5.2792],
        [5.1776, 5.8834, 5.2035]])



In [ ]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[0.6552, 0.5680, 0.6332, 0.2996, 0.7559],
        [0.5680, 0.5208, 0.6403, 0.2219, 0.7105],
        [0.6332, 0.6403, 1.2946, 0.3480, 0.8646],
        [0.2996, 0.2219, 0.3480, 0.2706, 0.2523],
        [0.7559, 0.7105, 0.8646, 0.2523, 0.9839]])

X*X^T  (2):
tensor([[0.6552, 0.5680, 0.6332, 0.2996, 0.7559],
        [0.5680, 0.5208, 0.6403, 0.2219, 0.7105],
        [0.6332, 0.6403, 1.2946, 0.3480, 0.8646],
        [0.2996, 0.2219, 0.3480, 0.2706, 0.2523],
        [0.7559, 0.7105, 0.8646, 0.2523, 0.9839]])



In [30]:
print(x.mm(x.t()))

tensor([[0.8405, 0.9646, 0.6834, 0.6683, 0.4354],
        [0.9646, 1.1373, 0.7532, 0.8312, 0.5824],
        [0.6834, 0.7532, 0.6150, 0.3960, 0.2458],
        [0.6683, 0.8312, 0.3960, 0.9098, 0.5912],
        [0.4354, 0.5824, 0.2458, 0.5912, 0.4710]])


In [31]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.4825, 0.5806, 0.3349, 0.5294, 0.3489])



In [32]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [33]:
torch.sum(torch.range(1, 10000) ** 2)

/home/fltww/anaconda3/envs/ML/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [34]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 2.6069e-08,  3.6057e-41,  1.2236e-08],
        [ 3.6057e-41, -2.4709e-11,  4.3791e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [35]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.7117, 0.8793, 0.3100],
        [0.2487, 0.0760, 0.0434],
        [0.6321, 0.5189, 0.3854],
        [0.1449, 0.1908, 0.4189],
        [0.0900, 0.9263, 0.3985]])


In [36]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [37]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [39]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [40]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-0.0981,  1.1083,  0.6875],
        [-2.4372,  1.8747, -0.8981],
        [-0.2984,  1.1545,  1.1865],
        [-1.0290, -1.1634,  0.5283],
        [-0.3032,  0.3045, -2.4208]]) torch.Size([5, 3])


## Задание 3

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [46]:
torch.manual_seed(42)

x = torch.rand(5, 3)

y = torch.rand(5, 3)

ans = x + y

print(ans[0][0])

tensor(1.3117)


In [ ]:
print(x * y) # поэлементное умножение

## Задание 4

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [47]:
ans = x.mm(y.t())

ans[-1][-1]

tensor(0.4885)

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
# b @ a